apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lock-test
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: lbacik/mutex-backend
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: REDIS_HOST
              value: "redis-srv.lock-test.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"

