apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lock-test
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
