apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lock-test
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: lbacik/mutex-worker:1.3.2
          imagePullPolicy: Always
          env:
            - name: BACKEND_URL
              value: http://backend-srv.lock-test.svc.cluster.local:8000
            - name: REDIS_HOST
              value: redis-srv.lock-test.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: LOCK
              value: no-lock
            - name: TTL
              value: "0"

